exclude:
  - .jekyll-cache

title: AxOps Technology Services
tagline: "pending"
description: "pending"

nav_logo: ./assets/img/axops-134x26.png
nav_logo2x: ./assets/img/axops-134x26@2x.png 2x

logo: /assets/img/axops-600x600.png
favicon: ./assets/img/favicons/favicon-32x32.png

logo_local: 
    image: /assets/img/axops-600x600.png
    symbol: "&Lambda;"
    text: "AxOps Technology Services"

url: https://www.axops.tech

twitter:
  username: 
  card: summary

social:
  name: AxOps
  links:
    - https://twitter.com/_insert_handle_here_
    - https://www.linkedin.com/in/_insert_handle_here_
    - https://github.com/axopstech

show_downloads: false
#paginate: 5

google_recaptcha:
    site_key: 