exclude:
  - .jekyll-cache

url: http://localhost:4000
title: AxOps Technologies
tagline: "pending"
description: "pending"

nav_logo: &url /assets/img/axops-134x26.png
nav_logo2x: &url /assets/img/axops-134x26@2x.png 2x

logo: &url /assets/img/axops-600x600.png
favicon: &url /assets/img/favicons/favicon-32x32.png

logo_local: 
    image: &url /assets/img/axops-600x600.png
    symbol: "&Lambda;"
    text: "AxOps Technologies"



twitter:
  username: 
  card: summary

social:
  name: AxOps
  links:
    - https://twitter.com/_insert_handle_here_
    - https://www.linkedin.com/in/_insert_handle_here_
    - https://github.com/axopstech

show_downloads: false
#paginate: 5

google_recaptcha:
    site_key: 